# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DaangnMarket-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DaangnMarket-iOS
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'JJFloatingActionButton'
  pod 'Alamofire'
  pod 'BSImagePicker', '~> 3.1' 
end
